#!/usr/bin/env bash

DIRECTORY=`dirname $0`

source $DIRECTORY/utils.bash

GITHUB_AUTH="claudusd:$TOKEN_GITHUB_COM"

if [ -f /etc/lsb-release ]; then
  source /etc/lsb-release
fi

function preInstall() {
  echo -e "$(writeUnderline 'Pre install:')"

  for package in $PRE_PACKAGE_NAME
  do
    if [ -f $DIRECTORY/list/$package.dependency ]; then 
      source $DIRECTORY/list/$package.dependency
      echo -e "$(writeBold ${DEPENDENCY_NAME})  -  $DEPENDENCY_DESCRIPTION"
      for subPackage in $DEPENDENCY_PACKAGE_NAME
      do 
        checkAptPackageInstalled $subPackage
        if [ $? = 0 ]; then
          echo -e "$(writeGreen ${CHAR_PACKAGE}) apt install ${subPackage} $(writeItalic "(installed)" )"
        else
          echo -e "$(writeRed ${CHAR_PACKAGE}) apt install ${subPackage}";
        fi;
      done
      echo
      clean_dependency_vars
    else 
      checkAptPackageInstalled $package
      if [ $? = 0 ]; then
        echo -e " $(writeGreen ${CHAR_PACKAGE}) apt install ${package} $(writeItalic "(installed)" )"
      else
        echo -e " $(writeRed ${CHAR_PACKAGE}) apt install ${package}";
      fi;
    fi
  done
}

function installation() {
  if [ -f "$DIRECTORY/list/$NAME.post_install" ] || [ -f "$DIRECTORY/list/$NAME.pre_install" ]; then 
    echo -e "$(writeUnderline 'Install:')"
  fi

  if [ -n "$GPG_PUBLIC_KEYS" ]; then
    echo "gpg2 --recv-keys $GPG_PUBLIC_KEYS"
  fi

  if [ -n "$INSTALL_URL" ]; then
    echo "Installation page : $INSTALL_URL";
  elif [ -n "$INSTALL_DEB_URL" ]; then
    INSTALL_DEB_URL=$(rewriteUrl $INSTALL_DEB_URL)
    echo "curl -L '$INSTALL_DEB_URL' -o /tmp/$NAME.deb"
    echo "dpkg -i /tmp/$NAME.deb"
    echo "rm /tmp/$NAME.deb"
  elif [ -n "$INSTALL_ZIP_URL" ]; then
    INSTALL_ZIP_URL=$(rewriteUrl $INSTALL_ZIP_URL)
    echo $INSTALL_ZIP_URL;
    echo "curl -L '$INSTALL_ZIP_URL' -o /tmp/$NAME.zip"
    echo "unzip /tmp/$NAME.zip -d /tmp/"
    echo "mv /tmp/$INSTALL_NAME /usr/local/bin/$INSTALL_NAME"
    echo "chmod +x /usr/local/bin/$INSTALL_NAME"
    echo "rm /tmp/$NAME.zip"
  elif [ -n "$INSTALL_COMMAND" ]; then
    echo "$INSTALL_COMMAND"
  elif [ -n "$GITHUB_REPO" ]; then
    installationFromGithubRelease
  elif [ -n "$PIP_PACKAGE" ]; then
    installationFromPip
  elif [ -n "$PACKAGE_NAME" ]; then

    if [ -n "$INSTALL_PACKAGE_REQUIRE" ]; then
        echo "apt install $INSTALL_PACKAGE_REQUIRE"
    fi

    if [ -n "$INSTALL_PPA" ]; then
        echo "add-apt-repository $INSTALL_PPA"
        echo "apt update"
    else
        if [ -n "$INSTALL_REPOSITORY_KEY" ]; then
            echo "wget -q -O- $INSTALL_REPOSITORY_KEY | sudo apt-key add -"
        fi;
        if [ -n "$INSTALL_REPOSITORY_URL" ]; then
            if [ -z "$INSTALL_REPOSITORY_DISTRO" ]; then
                INSTALL_REPOSITORY_DISTRO=$(lsb_release -sc)
            fi
	    checkSourceListUpdate
        REPOSITORY_ARCH=""
        if [ -n "$INSTALL_REPOSITORY_ARCH" ]; then
            REPOSITORY_ARCH="[arch=$INSTALL_REPOSITORY_ARCH]"
        fi
            echo "sudo sh -c 'echo \"deb $REPOSITORY_ARCH $INSTALL_REPOSITORY_URL $INSTALL_REPOSITORY_DISTRO $INSTALL_REPOSITORY_COMPONENT\" > /etc/apt/sources.list.d/$INSTALL_NAME.list'"
        unset REPOSITORY_ARCH
	    echo "apt update"
        fi;
    fi

    echo "apt install $PACKAGE_NAME $PACKAGE_NAME_EXTRA"
  fi

  if [ -f "$DIRECTORY/list/$NAME.post_install" ]; then
    echo -e "$(writeUnderline 'Post install:')"
    $DIRECTORY/list/$NAME.post_install
  fi

  if [ -n "$INSTALL_DOC" ]; then
    echo "$CHAR_BOOK $INSTALL_DOC"
  fi;
}

function rewriteUrl() {
  local URL=$1
  if [ -n "$GITHUB_REPO" ]; then 
    LATEST_VERSION=$(githubLatestRelease $GITHUB_REPO)
    URL=$(echo $URL | sed "s/--VERSION--/$LATEST_VERSION/g")
  fi
  echo $URL;
}

function checkVersionFromGithub() {
  LATEST_VERSION=$(githubLatestRelease $GITHUB_REPO)
  CURRENT_VERSION=$(getVersion $INSTALL_NAME)
  compareVersion $CURRENT_VERSION $LATEST_VERSION
  if [ $? -eq 1 ]; then
    newVersionAvailable $INSTALL_NAME "$CURRENT_VERSION" "$LATEST_VERSION"
  fi
  unset LATEST_VERSION;
  unset CURRENT_VERSION;
}

function checkVersionFromPip() {
  LATEST_VERSION=$(pipLatestRelease $PIP_PACKAGE)
  CURRENT_VERSION=$(getVersionPackagePip)
  compareVersion $CURRENT_VERSION $LATEST_VERSION
  if [ $? -eq 1 ]; then
    newVersionAvailable $INSTALL_NAME "$CURRENT_VERSION" "$LATEST_VERSION"
  fi
  unset LATEST_VERSION;
  unset CURRENT_VERSION;
}

function installationFromGithubRelease() {
  VERSION=$(githubLatestRelease $GITHUB_REPO)
  BIN_PATH="/usr/local/bin/$NAME"
  echo "curl -L 'https://github.com/$GITHUB_REPO/releases/download/$VERSION/$GITHUB_RELEASE_NAME' -o $BIN_PATH"
  echo "chmod +x $BIN_PATH"
  unset BIN_PATH
  unset VERSION
}

getVersionPackagePip() {
  INSTALL_DIR=$DOT_FILE_PATH
  INSTALL_DIR="$INSTALL_DIR/bin/pip/$NAME"

  local VET=$($INSTALL_DIR/.venv/bin/pip list | grep "^$PIP_PACKAGE ")
  VET=($VET)
  echo ${VET[1]}
}

function installationFromPip() {
  VERSION=$(pipLatestRelease $PIP_PACKAGE)
  INSTALL_DIR=$DOT_FILE_PATH
  INSTALL_DIR="$INSTALL_DIR/bin/pip/$NAME"
  echo "python3 -m venv $INSTALL_DIR/.venv"
  echo "$INSTALL_DIR/.venv/bin/pip install $PIP_PACKAGE==$VERSION"
  echo "echo -e '#!/usr/bin/env bash\nDIRECTORY=\`dirname \$0\`\nsource \$DIRECTORY/.venv/bin/activate\n\$DIRECTORY/.venv/bin/$INSTALL_NAME \$@' > $INSTALL_DIR/$INSTALL_NAME"
  echo "chmod +x $INSTALL_DIR/$INSTALL_NAME"
  echo "make dot-$NAME"
  unset INSTALL_DIR
  unset VERSION
}

function checkSourceListUpdate() {
  if [ -n "$INSTALL_REPOSITORY_URL" ]; then
    if [[ "$INSTALL_REPOSITORY_DISTRO" != $(lsb_release -sc) ]] && [[ "$INSTALL_REPOSITORY_DISTRO" != "stable" ]]; then
      RESULT=$(curl -s -o /dev/null -w "%{http_code}" "$INSTALL_REPOSITORY_URL/dists/$(lsb_release -sc)")
      if [ $RESULT -ne 404 ]; then
        echo -e "$(writeOrange $CHAR_WARNING) You can replace $(writeStrike $INSTALL_REPOSITORY_DISTRO) by $(lsb_release -sc)"
        INSTALL_REPOSITORY_DISTRO=$(lsb_release -sc)
      fi
    fi
  fi
}

function checkVersion() {
  if [ -n "$GITHUB_REPO" ]; then 
    checkVersionFromGithub $VERSION
  fi

  if [ -n "$PIP_PACKAGE" ]; then 
    checkVersionFromPip $VERSION
  fi
}

###
# @param bin
###
function check() {
  if [ -z "$INSTALL_NAME" ]; then
    INSTALL_NAME="$NAME"
  fi

  if [ -z "$PACKAGE_NAME" ]; then
      PACKAGE_NAME="$INSTALL_NAME";
  fi;

  checkInstalled $INSTALL_NAME

  if [ $? = 0 ]; then
    installed $NAME "$INSTALL_DESCRIPTION" $NAME_MAX_SIZE
    checkVersion
  else
    uninstalled $NAME "$INSTALL_DESCRIPTION" $NAME_MAX_SIZE
  fi;
}

clean_vars() {
  unset NAME;
  # Pre Install vars
  unset PRE_PACKAGE_NAME;
  # Install vars
  unset INSTALL_NAME;
  unset PACKAGE_NAME;
  unset INSTALL_DESCRIPTION;
  unset INSTALL_URL;
  unset INSTALL_DOC;
  unset INSTALL_REPOSITORY_URL;
  unset INSTALL_COMMAND;
  unset PACKAGE_NAME_EXTRA;
  unset INSTALL_PPA;
  unset INSTALL_PACKAGE_REQUIRE;
  unset INSTALL_REPOSITORY_DISTRO;
  unset INSTALL_REPOSITORY_COMPONENT;
  unset GPG_PUBLIC_KEYS;
  unset INSTALL_REPOSITORY_ARCH;
  unset GITHUB_REPO;
  unset GITHUB_RELEASE_NAME;
  unset INSTALL_REPOSITORY_KEY;
  unset PIP_PACKAGE;
}

clean_dependency_vars() {
  unset DEPENDENCY_NAME;
  unset DEPENDENCY_PACKAGE_NAME;
  unset DEPENDENCY_DESCRIPTION;
}

if ! which jq > /dev/null; then
	writeBold "Required package" 
	NAME="jq"
	INSTALL_DESCRIPTION="How read json in bash"
	check
	exit 
fi

if [ -z "$1" ]; then 
  NAME_MAX_SIZE=0
  for file in $DIRECTORY/list/*.install
  do
    NAME=$(basename $file);
    NAME=${NAME%.install}
    if [ $NAME_MAX_SIZE -le ${#NAME}  ]; then 
      NAME_MAX_SIZE=${#NAME}
    fi
  done

  for file in $DIRECTORY/list/*.install
  do
    if [ -f $file ]; then
        NAME=$(basename $file);
        NAME=${NAME%.install}
        source $file;
        check
        clean_vars;
    fi
  done
else
  if [ -f $DIRECTORY/list/$1.install ]; then
    NAME=$1
    NAME_MAX_SIZE=${#NAME}
    source $DIRECTORY/list/$1.install;
    check
    if [ -f "$DIRECTORY/list/$NAME.pre_install" ]; then
      source $DIRECTORY/list/$NAME.pre_install
      preInstall
    fi

    installation
    clean_vars;
  else 
    echo -e "$(writeRed "Cannot found install for ${1}")";
    exit 1
  fi  
fi
