#!/usr/bin/env bash

makefile_path="$(pwd)/makefile"

if [ -f "$makefile_path" ]; then
	echo "makefile already exist" 1>&2
	exit 1
fi;

cat << EOF > $makefile_path
PHONY: help

# self-documented makefile, thanks to the Marmelab team
# see http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
help:
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*\$\$' \$(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", \$\$1, \$\$2}'

dunny: ## Dunny
	@echo "Dunny"

EOF
