#!/usr/bin/env bash

DIRECTORY="`dirname "$0"`/../"

NAME=$1

if [ ! -d "$DIRECTORY/config/$NAME" ]; then 
    echo "Dotfile for $NAME doesn't exist"
    exit 1
fi


if [ -d "$DIRECTORY/config/$NAME/templates" ]; then
    CONFIG_JSON=$(cat "$DIRECTORY/config/$NAME/config.yml" | yq r  - --tojson)
    # echo $CONFIG_JSON
    for row in $(echo $CONFIG_JSON | jq -r '.variables[] | @base64'); do
        VAR=$(echo ${row} |  base64 -di)
        TYPE="$(echo $VAR | jq -r .type )"
        echo "$(echo $VAR | jq -r .description ) :" 
        if [ $TYPE == "password" ]; then 
            read -s $(echo $VAR | jq -r .name )
        else
            read $(echo $VAR | jq -r .name )
        fi
    done
    echo $CALDAV_USERNAME
    for row in $(echo $CONFIG_JSON | jq -r '.templates[] | @base64'); do
        TEMPLATE=$(echo ${row} |  base64 -di)
        INPUT_PATH="$DIRECTORY/config/$NAME/templates/$(echo $TEMPLATE | jq -r .src )"
        OUTPUT_DIR="$(echo $TEMPLATE | jq -r .dest)"
        OUTPUT_DIR="$(dirname $OUTPUT_DIR)"
        FILE_NAME=$(basename  $(echo $TEMPLATE | jq -r .dest))
        mkdir -p "$DIRECTORY/config/$NAME/output_template/$OUTPUT_DIR"
        while read line
        do
            eval echo "$line" >> "$DIRECTORY/config/$NAME/output_template/$OUTPUT_DIR/$FILE_NAME"
        done < "$INPUT_PATH"
        echo "Template $INPUT_PATH ->  $OUTPUT_DIR"
    done
fi

if [ -d "$DIRECTORY/config/$NAME/stow" ]; then 
    @stow -d "$DIRECTORY/config/$NAME/stow/" -t ~/ $NAME
fi