#!/usr/bin/env bash

DIRECTORY="$(realpath `dirname "$0"`/../)"
NAME=$1

if [ ! -d "$DIRECTORY/config/$NAME" ]; then 
    echo "Dotfile for $NAME doesn't exist"
    exit 1
fi


if [ -d "$DIRECTORY/config/$NAME/templates" ]; then
    CONFIG_JSON=$(cat "$DIRECTORY/config/$NAME/config.yml" | yq r  - --tojson)

    for row in $(echo $CONFIG_JSON | jq -r '.variables[] | @base64'); do
        VAR=$(echo ${row} |  base64 -di)
        TYPE="$(echo $VAR | jq -r .type )"
        echo "$(echo $VAR | jq -r .description ) :" 
        if [ $TYPE == "password" ]; then 
            read -s $(echo $VAR | jq -r .name )
        else
            read $(echo $VAR | jq -r .name )
        fi
    done

    for row in $(echo $CONFIG_JSON | jq -r '.templates[] | @base64'); do
        TEMPLATE=$(echo ${row} |  base64 -di)
        INPUT_PATH="$DIRECTORY/config/$NAME/templates/$(echo $TEMPLATE | jq -r .src )"
        OUTPUT_DIR="$(echo $TEMPLATE | jq -r .dest)"
        OUTPUT_DIR="$(dirname $OUTPUT_DIR)"
        FILE_NAME=$(basename  $(echo $TEMPLATE | jq -r .dest))
        mkdir -p "$DIRECTORY/config/$NAME/output_template/$OUTPUT_DIR"

        if [ -f $DIRECTORY/config/$NAME/output_template/$OUTPUT_DIR/$FILE_NAME ]; then
            rm $DIRECTORY/config/$NAME/output_template/$OUTPUT_DIR/$FILE_NAME
        fi

        while read line
        do
            line_quoted=$(echo "${line//\"/\\\"}")
            eval echo $line_quoted >> "$DIRECTORY/config/$NAME/output_template/$OUTPUT_DIR/$FILE_NAME"
        done < "$INPUT_PATH"
    done
    stow -d "$DIRECTORY/config/$NAME/" -t ~/ output_template
fi

if [ -d "$DIRECTORY/config/$NAME/directories" ]; then 
    CONFIG_JSON=$(cat "$DIRECTORY/config/$NAME/config.yml" | yq r  - --tojson)
    for row in $(echo $CONFIG_JSON | jq -r '.directories[] | @base64'); do
        DIRECTORY_JSON=$(echo ${row} | base64 -di)
        SRC=$(echo $DIRECTORY_JSON | jq -r .src)
        DEST=$(echo $DIRECTORY_JSON | jq -r .dest)
        if [ -d "$DIRECTORY/config/$NAME/directories/$SRC" ]; then
            DEST_PARENT=$(dirname $DEST)
            DEST_PARENT=$(echo "${DEST_PARENT//\~/$HOME}")
            mkdir -p "$DEST_PARENT"
            DEST=$(echo "${DEST//\~/$HOME}")
            if [ ! -L $DEST ]; then
                ln -s $DIRECTORY/config/$NAME/directories/$SRC $DEST
            fi
        fi
    done
fi

if [ -d "$DIRECTORY/config/$NAME/stow" ]; then 
    stow -d "$DIRECTORY/config/$NAME/" -t ~/ stow
fi
