#!/usr/bin/env bash
DIRECTORY=`dirname $0`

source $DIRECTORY/../lib/utils.bash

function toOld() {
    if [ ! -f $1 ]; then
        return 0
    fi

    if test `find "$1" -mmin +1`
    then
        rm $1
        return 0
    fi

    return 1
}

function listIssueGithub() {
    FILE_TMP="/tmp/github.issue"
    toOld $FILE_TMP
    if [ $? -eq 0 ]; then
        curl -u claudusd:${TOKEN_GITHUB_COM} https://api.github.com/orgs/clermontech/issues > $FILE_TMP 2> /dev/null
    fi;

    for row in $(cat $FILE_TMP | jq -r '.[] | @base64'); do
        ISSUE=$(echo ${row} |  base64 -di)
        echo $(echo $ISSUE | jq -r .title ) "("$(echo $ISSUE | jq -r .id )")"
        echo "$(echo $ISSUE | jq -r .html_url )"
        echo
    done
}

function listIssueGitlab() {
    FILE_TMP=$2
    toOld $FILE_TMP
    if [ $? -eq 0 ]; then
        curl --header "PRIVATE-TOKEN: $1" $3/api/v4/groups/$4/issues?assignee_username=$5 > $FILE_TMP 2> /dev/null
    fi;

    for row in $(cat $FILE_TMP | jq -r '.[] | @base64'); do
        ISSUE=$(echo ${row} |  base64 -di)
        echo $(echo $ISSUE | jq -r .title ) "("$(echo $ISSUE | jq -r .id )")"
        echo "$(echo $ISSUE | jq -r .web_url )"
        echo 
    done
}


echo -e "$(writeBold 'Volcamp')"
listIssueGitlab $TOKEN_GITLAB_COM "/tmp/gitlab.com.issue" "https://gitlab.com" "6927305" "claudusd1"

echo -e "$(writeBold 'CRI')"
listIssueGitlab $TOKEN_GITLAB_ISIMA_FR "/tmp/gitlab.isima.fr.issue" "https://gitlab.isima.fr" "13" "cladioud1"

echo -e "$(writeBold 'Clermontech')"
listIssueGithub