#!/usr/bin/env bash

function toOld() {
    if test `find "$1" -mmin +1`
    then
        rm $1
        return 0
    fi

    return 1
}

function listIssueGithub() {
  echo "curl -L 'https://github.com/$GITHUB_REPO/releases/download/$VERSION/$GITHUB_RELEASE_NAME' -o $BIN_PATH"
}

function listIssueGitlab() {
    FILE_TMP="/tmp/gitlab.issue"
    toOld $FILE_TMP
    if [ $? -eq 0 ]; then
        echo "Use new"
        curl --header "PRIVATE-TOKEN: $TOKEN_GITLAB_COM" https://gitlab.com/api/v4/groups/6927305/issues?assignee_username=claudusd1 > $FILE_TMP 2> /dev/null
    fi;


    
}

listIssueGitlab