#!/usr/bin/env bash
DIRECTORY=`dirname $0`

source $DIRECTORY/../lib/utils.bash

function toOld() {
    if [ ! -f $1 ]; then
        return 0
    fi

    if test `find "$1" -mmin +1`
    then
        rm $1
        return 0
    fi

    return 1
}

function listIssueGithub() {
    FILE_TMP="/tmp/github.issue"
    toOld $FILE_TMP
    if [ $? -eq 0 ]; then
        curl -u claudusd:${TOKEN_GITHUB_COM} https://api.github.com/orgs/clermontech/issues > $FILE_TMP 2> /dev/null
    fi;

    for row in $(cat $FILE_TMP | jq -r '.[] | @base64'); do
        ISSUE=$(echo ${row} |  base64 -di)
        echo $(echo $ISSUE | jq -r .title ) "("$(echo $ISSUE | jq -r .id )")"
    done
}

function listIssueGitlab() {
    FILE_TMP="/tmp/gitlab.issue"
    toOld $FILE_TMP
    if [ $? -eq 0 ]; then
        curl --header "PRIVATE-TOKEN: $TOKEN_GITLAB_COM" https://gitlab.com/api/v4/groups/6927305/issues?assignee_username=claudusd1 > $FILE_TMP 2> /dev/null
    fi;

    for row in $(cat $FILE_TMP | jq -r '.[] | @base64'); do
        ISSUE=$(echo ${row} |  base64 -di)
        echo $(echo $ISSUE | jq -r .title ) "("$(echo $ISSUE | jq -r .id )")"
    done

}

echo "VOLCAMP"
listIssueGitlab

echo "Clermontech"
listIssueGithub